# Generated by Django 3.0.5 on 2020-04-27 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('hour', models.IntegerField(verbose_name='Часы')),
                ('semester', models.IntegerField(choices=[(1, 'Kurs 1 Sem 1'), (2, 'Kurs 1 Sem 2'), (3, 'Kurs 2 Sem 1'), (4, 'Kurs 2 Sem 2'), (5, 'Kurs 3 Sem 1'), (6, 'Kurs 3 Sem 2'), (7, 'Kurs 4 Sem 1'), (8, 'Kurs 4 Sem 2'), (9, 'Kurs 5 Sem 1'), (10, 'Kurs 5 Sem 2'), (11, 'Kurs 6 Sem 1'), (12, 'Kurs 6 Sem 2')], verbose_name='Семестр')),
            ],
            options={
                'verbose_name': 'предмет обучения',
                'verbose_name_plural': 'предметы обучения',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'университет',
                'verbose_name_plural': 'университеты',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('kurs', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth'), (6, 'Sixth')], verbose_name='Курс')),
                ('stipend', models.IntegerField(verbose_name='Стипендия')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.University', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'студент',
                'verbose_name_plural': 'студенты',
            },
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('subjects', models.ManyToManyField(to='app.Subject', verbose_name='Предметы')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.University', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'преподаватель',
                'verbose_name_plural': 'преподаватели',
            },
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(choices=[(1, 'Mark 1'), (2, 'Mark 2'), (3, 'Mark 3'), (4, 'Mark 4'), (5, 'Mark 5')], verbose_name='Оценка')),
                ('date', models.DateField(verbose_name='Дата')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Student', verbose_name='Студент')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'оценка по экзамену',
                'verbose_name_plural': 'оценки по экзамену',
            },
        ),
    ]
